name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Deployment targets (choose one)
        required: true
        default: all_tests
        type: choice
        options:
          - all_tests
          - regression

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: all_tests
      if: "'all_tests' == github.event.inputs.deployment_target"
      run: |
        pytest --alluredir=allure-results
    - name: regression
      if: "'regression' == github.event.inputs.deployment_target"
      run: |
        pytest -m regression --alluredir=allure-results
    - name: Uploading test artifacts
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: 'allure-results'
        path: allure-results
        retention-days: 1
